name: Deploy to GitHub Pages

on:
  push:
    branches: [main]
    paths:
      - "public/**"
      - "src/**"
      - "astro.config.ts"
      - "pnpm-lock.yaml"
      - "tsconfig.json"
  workflow_dispatch: {}

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    environment: main
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6.0.2
      - name: Install, build, and upload your site output
        uses: withastro/action@v5.2.0
        with:
          node-version: 24
          package-manager: pnpm@latest
        env:
          ASTRO_SITE: ${{ vars.PUBLIC_URL }}

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4.0.5
